export const AGGREGATOR_ENDPOINT = process.env.AGGREGATOR_ENDPOINT
export const TRANSACTIONS_ENDPOINT = AGGREGATOR_ENDPOINT + '/transactions'
export const BLOCKS_ENDPOINT = AGGREGATOR_ENDPOINT + '/blocks'
